---
# Below are examples. Replace them with your own backup configurations

backup_configs:
  - borg_repository_name: jellyfin
    borg_repository_passphrase: "{{ borg_repository_jellyfin_passphrase }}"

  - borg_repository_name: nextcloud
    borg_repository_passphrase: "{{ borg_repository_nextcloud_passphrase }}"
    sql_dump:
      dump_folder_path_within_borg_repository: /var/docker_volumes/nextcloud
