---
# Below are examples. Replace them with your own backup configurations

send_email_on_failure: true
send_email_on_success: true
borg_repositories:
  - name: jellyfin
    passphrase: "{{ borg_repository_jellyfin_passphrase }}"
    file_paths_to_check:
      - /var/docker_volumes/jellyfin/config/root/default/Movies/options.xml

  - name: nextcloud
    passphrase: "{{ borg_repository_nextcloud_passphrase }}"
    sql_dump_folder_path: /var/docker_volumes/nextcloud
